### ISSUE TITLE
FedGLUE dataset

### ISSUE THREAD

**Issue by tzc0029** [iezhuozhuo/FedETuning#2]
Thank you for sharing the implementation. Could you also show me where to download or prepare the FedGLUE dataset?

**Comment by iezhuozhuo** [comment]
Hi,

Thanks for following our work! The data link is in:
https://drive.google.com/file/d/1wN9Mg3up_CqhnaO6UIsZOXUI72MyVSAH/

Best,
Zhuo


Tianshi Che ***@***.***> 于2023年5月16日周二 23:46写道：
